# This file is under your control.  Its main use is to define variables that
# are used by 'premake', such as MK_PREMAKE.*, MK_VARIANTS.* and
# MK_PREMAKE_HELP.*

# Directory to load build flavors from.
MK_FLAVOR_DIR := build/flavor

include ../mk/lib/premake.mk
